services:
  nginx:
    image: nginx:latest
    container_name: test-proxy
    restart: "no"
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-server
      - go-server

  node-server:
    image: node:latest
    container_name: node-server
    command: ["node", "index.js"]
    volumes:
      - ./node-server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"

  go-server:
    image: golang:latest
    container_name: go-server
    command: ["go", "run", "main.go"]
    volumes:
      - ./go-server:/go/src/app
    working_dir: /go/src/app
    ports:
      - "4000:4000"
